// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWil221PtykthkBOxtrvYr9kTnYnGiIpw',
    appId: '1:533538732954:web:1d0340fe6451bba08d5823',
    messagingSenderId: '533538732954',
    projectId: 'electrify-eef90',
    authDomain: 'electrify-eef90.firebaseapp.com',
    databaseURL: 'https://electrify-eef90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electrify-eef90.appspot.com',
    measurementId: 'G-X8BW9DMPP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTKKVoN_SDFDm8ikmX08XTQcy_ee9nd8',
    appId: '1:533538732954:android:3d664b5aa86f25a68d5823',
    messagingSenderId: '533538732954',
    projectId: 'electrify-eef90',
    databaseURL: 'https://electrify-eef90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electrify-eef90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsMl7P0InUXUCGzipLbJEW_Rc-yJYpHQY',
    appId: '1:533538732954:ios:b4d338a9c309a5938d5823',
    messagingSenderId: '533538732954',
    projectId: 'electrify-eef90',
    databaseURL: 'https://electrify-eef90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electrify-eef90.appspot.com',
    iosClientId: '533538732954-n4an6902e81fk76g2lsib31ggoecajpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.electrifyy',
  );
}
